"""v2

Revision ID: 28179e076c27
Revises: 6abc60dba3e2
Create Date: 2021-07-11 17:26:58.888910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28179e076c27'
down_revision = '6abc60dba3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('good', sa.Integer(), nullable=True))
    op.add_column('board', sa.Column('bad', sa.Integer(), nullable=True))
    op.add_column('recommend', sa.Column('used', sa.Boolean(), nullable=False))
    op.add_column('recommend', sa.Column('ip', sa.String(length=96), nullable=True))
    op.add_column('reply', sa.Column('good', sa.Integer(), nullable=True))
    op.add_column('reply', sa.Column('bad', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reply', 'bad')
    op.drop_column('reply', 'good')
    op.drop_column('recommend', 'ip')
    op.drop_column('recommend', 'used')
    op.drop_column('board', 'bad')
    op.drop_column('board', 'good')
    # ### end Alembic commands ###
