"""v5

Revision ID: 4ecd294b84b0
Revises: 5e9e86719533
Create Date: 2021-07-15 09:10:47.184106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ecd294b84b0'
down_revision = '5e9e86719533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('is_onetime', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('expire', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('idx')
    )
    op.add_column('board', sa.Column('is_notice', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'is_notice')
    op.drop_table('token')
    # ### end Alembic commands ###
